### ISSUE TITLE
DoneJS + CanJS

### ISSUE THREAD

**Issue by sporto** [devchattv/jsjabbertopics#10]
DoneJS is an open source JavaScript framework that makes it easy to build high performance, real-time web and mobile applications.

http://donejs.com/

This framework has never been covered but it has been around for a while and it is quite good (I have used CanJS extensively in the past). I would love to hear an episode about it now that they have finished 'DoneJS'.

**Comment by BigAB** [comment]
:+1:
Guest Recommendation: Justin Meyer @justinbmeyer or Brian Moschel @moschel

**Comment by moschel** [comment]
:+1:

**Comment by jedh** [comment]
+1

**Comment by TasikBeyond** [comment]
+1

**Comment by jwutke** [comment]
+1. I'd like to know more about it.

**Comment by bryanbierce** [comment]
<img class="emoji" title=":+1:" alt=":+1:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png" height="20" width="20" align="absmiddle">

**Comment by kikoanis** [comment]
:+1:

**Comment by abalmus** [comment]
+1

**Comment by phillipskevin** [comment]
:+1:

**Comment by pYr0x** [comment]
+1

**Comment by jason2345** [comment]
:+1:

**Comment by cherifGsoul** [comment]
:+1:

**Comment by dylanrtt** [comment]
+1

**Comment by benregn** [comment]
:+1:

**Comment by justinbmeyer** [comment]
:+1: I'd be happy to talk about it.

**Comment by DesignByOnyx** [comment]
:+1:

**Comment by smiper** [comment]
:+1:

**Comment by jeroencornelissen** [comment]
:thumbsup:

**Comment by xedoken** [comment]
+1

**Comment by marshallswain** [comment]
+1

**Comment by akagomez** [comment]
+1

**Comment by m-mujica** [comment]
:+1:

**Comment by dbleier** [comment]
+1

**Comment by ilyavf** [comment]
+1

**Comment by mjstahl** [comment]
:+1:

**Comment by therubyrep** [comment]
Emailed @justinbmeyer 1/25/16

**Comment by robertheessels** [comment]
+1

**Comment by marshallswain** [comment]
:+1:

**Comment by smoothlikejazz** [comment]
+1

**Comment by cmaxw** [comment]
Recorded 03/01/2016
