### ISSUE TITLE
Electron, Atom, and JS desktop apps

### ISSUE THREAD

**Issue by rayners** [devchattv/jsjabbertopics#3]
I'd love to hear about using JavaScript outside web pages and server back ends.

**Comment by stefanjudis** [comment]
:+1 :

**Comment by cmaxw** [comment]
We're talking to Amy Palamountain and Jessica Lord to get this on the schedule.

**Comment by arthurakay** [comment]
I'm not a contributor of Atom or Electron, but I've become very familiar with Electron over the past year. I'd be happy to be a part of the show and offer some insight from my own experience.

Same goes with nwjs (formerly node-webkit) -- I've been using both projects, so maybe a compare/contrast segment might be interesting.

**Comment by fonzerelly** [comment]
+1

**Comment by liubko** [comment]
+1

**Comment by chris--young** [comment]
+1

**Comment by kawanoshinobu** [comment]
+1

**Comment by barsukov** [comment]
+1

**Comment by bb** [comment]
+1

**Comment by btav** [comment]
+1

**Comment by cmaxw** [comment]
https://devchat.tv/js-jabber/193-jsj-electron-with-jessica-lord-and-amy-palamountain
